#!/usr/bin/env bash
# configures a new ubuntu machine to run an nginx server
sudo apt-get install -y nginx 
echo "Hello World!" > index.html
sudo mv index.html /var/www/html
sudo service nginx restart
