#!/usr/bin/env bash
# configures a server to redirect /redirect_me
sudo apt-get update
sudo apt-get install -y nginx 
echo "Hello World!" > index.html
sudo mv index.html /var/www/html

#shellcheck disable=SC2016
echo 'server {
   listen 80 default_server;
   listen [::]:80 default_server;
   
   root /var/www/html;
   index index.html;
   add_header X-Served-By $hostname;
}' > default
sudo mv -f default /etc/nginx/sites-available/default
sudo service nginx restart
