#!/usr/bin/env bash
#econfigures haproxy on a server
apt update
apt install -y haproxy
echo "\
frontend http
   bind *:80
   default_backend web-backend

backend web-backend
   balance roundrobin
   server web-01 18.208.159.79:80 check
   server web-02 34.239.158.102:80 check
" | tee -a /etc/haproxy/haproxy.cfg

service haproxy restart

