#!/usr/bin/env bash
#runs nginx as nginx user on port 8080
chmod 0644 /etc/nginx/nginx.conf
sed -i "s/#user www-data/user nginx/" /etc/nginx/nginx.conf
sed -i "s/80/8080/" /etc/nginx/sites-available/default
pkill apache2
sudo -u nginx service nginx restart
